### ISSUE TITLE
Crashing on Galaxy S4 (I337) "Resources Not Found Exception"

### ISSUE THREAD

**Issue by paulpjryan** [romannurik/muzei#165]
This crash happens as soon as I try to open the "Settings" or "Customize" option. Here is the log output:

```
06-29 18:32:01.566  17077-17077/? E/AndroidRuntime﹕ FATAL EXCEPTION: main
    Process: net.nurik.roman.muzei, PID: 17077
    android.content.res.Resources$NotFoundException: String resource ID #0x0
            at android.content.res.Resources.getText(Resources.java:1334)
            at android.content.res.Resources.getString(Resources.java:1428)
            at com.google.android.apps.muzei.settings.SettingsChooseSourceFragment.updateSources(SettingsChooseSourceFragment.java:363)
            at com.google.android.apps.muzei.settings.SettingsChooseSourceFragment.onResume(SettingsChooseSourceFragment.java:226)
            at android.app.Fragment.performResume(Fragment.java:2162)
            at android.app.FragmentManagerImpl.moveToState(FragmentManager.java:943)
            at android.app.FragmentManagerImpl.moveToState(FragmentManager.java:1082)
            at android.app.BackStackRecord.run(BackStackRecord.java:833)
            at android.app.FragmentManagerImpl.execPendingActions(FragmentManager.java:1467)
            at android.app.FragmentManagerImpl$1.run(FragmentManager.java:452)
            at android.os.Handler.handleCallback(Handler.java:739)
            at android.os.Handler.dispatchMessage(Handler.java:95)
            at android.os.Looper.loop(Looper.java:145)
            at android.app.ActivityThread.main(ActivityThread.java:5942)
            at java.lang.reflect.Method.invoke(Native Method)
            at java.lang.reflect.Method.invoke(Method.java:372)
            at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1399)
            at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1194)
```

The device is running Android 5.0.1 on baseband OC3.

**Comment by mobbren** [comment]
```java
public void updateSources() {
        mSelectedSource = null;
        Intent queryIntent = new Intent(ACTION_MUZEI_ART_SOURCE);
        PackageManager pm = getActivity().getPackageManager();
        mSources.clear();
        List<ResolveInfo> resolveInfos = pm.queryIntentServices(queryIntent,
                PackageManager.GET_META_DATA);

        for (ResolveInfo ri : resolveInfos) {
            Source source = new Source();
            source.label = ri.loadLabel(pm).toString();
            source.icon = new BitmapDrawable(getResources(), generateSourceImage(ri.loadIcon(pm)));
            source.componentName = new ComponentName(ri.serviceInfo.packageName,
                    ri.serviceInfo.name);
            Context packageContext;
            try {
                packageContext = getActivity().createPackageContext(
                        source.componentName.getPackageName(), 0);
                Resources packageRes = packageContext.getResources();

                // BUG IS HERE
                source.description = packageRes.getString(ri.serviceInfo.descriptionRes);
                // -----

            } catch (PackageManager.NameNotFoundException e) {
                LOGW(TAG, "Can't read package resources for source " + source.componentName);
            }
            Bundle metaData = ri.serviceInfo.metaData;
            source.color = Color.WHITE;
            if (metaData != null) {
                String settingsActivity = metaData.getString("settingsActivity");
                if (!TextUtils.isEmpty(settingsActivity)) {
                    source.settingsActivity = ComponentName.unflattenFromString(
                            ri.serviceInfo.packageName + "/" + settingsActivity);
                }

                source.color = metaData.getInt("color", source.color);

                try {
                    float[] hsv = new float[3];
                    Color.colorToHSV(source.color, hsv);
                    boolean adjust = false;
                    if (hsv[2] < 0.8f) {
                        hsv[2] = 0.8f;
                        adjust = true;
                    }
                    if (hsv[1] > 0.4f) {
                        hsv[1] = 0.4f;
                        adjust = true;
                    }
                    if (adjust) {
                        source.color = Color.HSVToColor(hsv);
                    }
                    if (Color.alpha(source.color) != 255) {
                        source.color = Color.argb(255,
                                Color.red(source.color),
                                Color.green(source.color),
                                Color.blue(source.color));
                    }
                } catch (IllegalArgumentException ignored) {
                }
            }

            mSources.add(source);
        }
```

**Comment by ianhanniballake** [comment]
Can you please report this to whatever extension you have loaded? Seems that an `android:description` on the `MuzeiArtSource` is required to prevent this error from occurring and Muzei is crashing because that field does not exist in one of the extensions on your device.

**Comment by dahoba** [comment]
I faced the same Exception. After clone this repo and do debugging. Finally I found the trouble maker, it's The Materis - Icon Pack (v 1.1.1). After uninstall Muzei is able to enter the settings screen.

**Comment by paulpjryan** [comment]
I do use Materis Icon Pack! That is probably the issue. Thanks.
