### ISSUE TITLE
Android M Permission Issue

### ISSUE THREAD

**Issue by Andrew-Quebe** [romannurik/muzei#179]
I'm not entirely sure if this is 100% accurate but there appears to be a permission issue on Android M which is causing a crash to occur. I've talked with my fellow developer friends who run Lollipop and they say there's no issue. I was able to pull this error off the logcat:

```
09-21 23:37:48.276 15354-15354/? E/AndroidRuntime: FATAL EXCEPTION: main
09-21 23:37:48.276 15354-15354/? E/AndroidRuntime: Process: net.nurik.roman.muzei, PID: 15354
09-21 23:37:48.276 15354-15354/? E/AndroidRuntime: java.lang.RuntimeException: Unable to create application com.google.android.apps.muzei.MuzeiApplication: java.lang.SecurityException: Not allowed to start service Intent { act=com.google.android.apps.muzei.api.action.SUBSCRIBE cmp=com.daviidh.android.wallpaper/wallpaper.android.daviidh.com.evolvewallpapers.muzei.ArtSource (has extras) } without permission none
09-21 23:37:48.276 15354-15354/? E/AndroidRuntime:     at android.app.ActivityThread.handleBindApplication(ActivityThread.java:4710)
09-21 23:37:48.276 15354-15354/? E/AndroidRuntime:     at android.app.ActivityThread.-wrap1(ActivityThread.java)
09-21 23:37:48.276 15354-15354/? E/AndroidRuntime:     at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1405)
09-21 23:37:48.276 15354-15354/? E/AndroidRuntime:     at android.os.Handler.dispatchMessage(Handler.java:102)
09-21 23:37:48.276 15354-15354/? E/AndroidRuntime:     at android.os.Looper.loop(Looper.java:148)
09-21 23:37:48.276 15354-15354/? E/AndroidRuntime:     at android.app.ActivityThread.main(ActivityThread.java:5417)
09-21 23:37:48.276 15354-15354/? E/AndroidRuntime:     at java.lang.reflect.Method.invoke(Native Method)
09-21 23:37:48.276 15354-15354/? E/AndroidRuntime:     at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
09-21 23:37:48.276 15354-15354/? E/AndroidRuntime:     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)
09-21 23:37:48.276 15354-15354/? E/AndroidRuntime:  Caused by: java.lang.SecurityException: Not allowed to start service Intent { act=com.google.android.apps.muzei.api.action.SUBSCRIBE cmp=com.daviidh.android.wallpaper/wallpaper.android.daviidh.com.evolvewallpapers.muzei.ArtSource (has extras) } without permission none
09-21 23:37:48.276 15354-15354/? E/AndroidRuntime:     at android.app.ContextImpl.startServiceCommon(ContextImpl.java:1245)
09-21 23:37:48.276 15354-15354/? E/AndroidRuntime:     at android.app.ContextImpl.startService(ContextImpl.java:1222)
09-21 23:37:48.276 15354-15354/? E/AndroidRuntime:     at android.content.ContextWrapper.startService(ContextWrapper.java:581)
09-21 23:37:48.276 15354-15354/? E/AndroidRuntime:     at com.google.android.apps.muzei.SourceManager.subscribeToSelectedSource(SourceManager.java:217)
09-21 23:37:48.276 15354-15354/? E/AndroidRuntime:     at com.google.android.apps.muzei.MuzeiApplication.onCreate(MuzeiApplication.java:34)
09-21 23:37:48.276 15354-15354/? E/AndroidRuntime:     at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1013)
09-21 23:37:48.276 15354-15354/? E/AndroidRuntime:     at android.app.ActivityThread.handleBindApplication(ActivityThread.java:4707)
09-21 23:37:48.276 15354-15354/? E/AndroidRuntime:     at android.app.ActivityThread.-wrap1(ActivityThread.java) 
09-21 23:37:48.276 15354-15354/? E/AndroidRuntime:     at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1405) 
09-21 23:37:48.276 15354-15354/? E/AndroidRuntime:     at android.os.Handler.dispatchMessage(Handler.java:102) 
09-21 23:37:48.276 15354-15354/? E/AndroidRuntime:     at android.os.Looper.loop(Looper.java:148) 
09-21 23:37:48.276 15354-15354/? E/AndroidRuntime:     at android.app.ActivityThread.main(ActivityThread.java:5417) 
09-21 23:37:48.276 15354-15354/? E/AndroidRuntime:     at java.lang.reflect.Method.invoke(Native Method) 
09-21 23:37:48.276 15354-15354/? E/AndroidRuntime:     at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726) 
09-21 23:37:48.276 15354-15354/? E/AndroidRuntime:     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616) 
09-21 23:37:48.329 13054-13080/? E/Surface: getSlotFromBufferLocked: unknown buffer: 0xb373a470
```

Note that `wallpaper.android.daviidh.com.evolvewallpapers.muzei.ArtSource` is the package name of my custom app. 

I've checked the permissions section in the app info screen and it says Storage is turned on but there isn't anything else. Is this a permission issue?

**Comment by ianhanniballake** [comment]
It sounds like your MuzeiArtSource does not have `exported="true"``

**Comment by Andrew-Quebe** [comment]
I check my code and the settings activity that's opened through Muzei does have the `exported="true"` attribute. However, `MuzeiArtSource` does not because it's a service. Do I set the service as exported as well?

Should also note, the service doesn't have exported defined anywhere...the settings activity does.

**Comment by Andrew-Quebe** [comment]
Just tried the above and it works! Thanks for helping me out.
