### ISSUE TITLE
The app crashes upon clicking on ACTIVATE

### ISSUE THREAD

**Issue by liobash** [romannurik/muzei#537]
#### Expected behavior
The application is expected to work flawlessly while using.

#### Actual behavior
The application suddenly crash the moment the **ACTIVATE** button is clicked on 

#### How to reproduce
- Launch the application 
- Wait for it to load
- Click on **ACTIVATE**
- The crash occurs 

* Browser/App version: 2.5.2
* Operating system: Teckno k8

#### Recording Of The Bug

https://youtu.be/gL0yLdMZ_HY

## Note
The application works fine on first launch. However after exploring for sometime, this crash becomes effective non stop

Should in case you tried and you could not locate the crash on first launch. The logcat provided below hold the rest of the information.
### LOG 
```05-29 17:01:07.942 26937 27020 E AndroidRuntime: FATAL EXCEPTION: AsyncTask #1
05-29 17:01:07.942 26937 27020 E AndroidRuntime: Process: net.nurik.roman.muzei, PID: 26937
05-29 17:01:07.942 26937 27020 E AndroidRuntime: java.lang.RuntimeException: An error occurred while executing doInBackground()
05-29 17:01:07.942 26937 27020 E AndroidRuntime: 	at android.os.AsyncTask$3.done(AsyncTask.java:318)
05-29 17:01:07.942 26937 27020 E AndroidRuntime: 	at java.util.concurrent.FutureTask.finishCompletion(FutureTask.java:354)
05-29 17:01:07.942 26937 27020 E AndroidRuntime: 	at java.util.concurrent.FutureTask.setException(FutureTask.java:223)
05-29 17:01:07.942 26937 27020 E AndroidRuntime: 	at java.util.concurrent.FutureTask.run(FutureTask.java:242)
05-29 17:01:07.942 26937 27020 E AndroidRuntime: 	at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:243)
05-29 17:01:07.942 26937 27020 E AndroidRuntime: 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133)
05-29 17:01:07.942 26937 27020 E AndroidRuntime: 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607)
05-29 17:01:07.942 26937 27020 E AndroidRuntime: 	at java.lang.Thread.run(Thread.java:761)
05-29 17:01:07.942 26937 27020 E AndroidRuntime: Caused by: java.lang.SecurityException: Unable to start service Intent { act=com.google.android.apps.muzei.api.action.SUBSCRIBE cmp=de.devmil.muzei.bingimageofthedayartsource/de.devmil.muzei.bingimageoftheday.BingImageOfTheDayArtSource (has extras) }: AMS: *** Unable to launch app de.devmil.muzei.bingimageofthedayartsource/10155 for service Intent { act=com.google.android.apps.muzei.api.action.SUBSCRIBE cmp=de.devmil.muzei.bingimageofthedayartsource/de.devmil.muzei.bingimageoftheday.BingImageOfTheDayArtSource }, from net.nurik.roman.muzei/10156: AutoStart Limited.
05-29 17:01:07.942 26937 27020 E AndroidRuntime: 	at android.app.ContextImpl.startServiceCommon(ContextImpl.java:1397)
05-29 17:01:07.942 26937 27020 E AndroidRuntime: 	at android.app.ContextImpl.startService(ContextImpl.java:1370)
05-29 17:01:07.942 26937 27020 E AndroidRuntime: 	at android.content.ContextWrapper.startService(ContextWrapper.java:613)
05-29 17:01:07.942 26937 27020 E AndroidRuntime: 	at com.google.android.apps.muzei.SourceManager.unsubscribe(SourceManager.java:229)
05-29 17:01:07.942 26937 27020 E AndroidRuntime: 	at com.google.android.apps.muzei.SourceManager.access$100(SourceManager.java:53)
05-29 17:01:07.942 26937 27020 E AndroidRuntime: 	at com.google.android.apps.muzei.SourceManager$3.doInBackground(SourceManager.java:133)
05-29 17:01:07.942 26937 27020 E AndroidRuntime: 	at com.google.android.apps.muzei.SourceManager$3.doInBackground(SourceManager.java:118)
05-29 17:01:07.942 26937 27020 E AndroidRuntime: 	at android.os.AsyncTask$2.call(AsyncTask.java:304)
05-29 17:01:07.942 26937 27020 E AndroidRuntime: 	at java.util.concurrent.FutureTask.run(FutureTask.java:237)
05-29 17:01:07.942 26937 27020 E AndroidRuntime: 	... 4 more
05-29 17:01:35.679 27194 27274 E AndroidRuntime: FATAL EXCEPTION: AsyncTask #1
05-29 17:01:35.679 27194 27274 E AndroidRuntime: Process: net.nurik.roman.muzei, PID: 27194
05-29 17:01:35.679 27194 27274 E AndroidRuntime: java.lang.RuntimeException: An error occurred while executing doInBackground()
05-29 17:01:35.679 27194 27274 E AndroidRuntime: 	at android.os.AsyncTask$3.done(AsyncTask.java:318)
05-29 17:01:35.679 27194 27274 E AndroidRuntime: 	at java.util.concurrent.FutureTask.finishCompletion(FutureTask.java:354)
05-29 17:01:35.679 27194 27274 E AndroidRuntime: 	at java.util.concurrent.FutureTask.setException(FutureTask.java:223)
05-29 17:01:35.679 27194 27274 E AndroidRuntime: 	at java.util.concurrent.FutureTask.run(FutureTask.java:242)
05-29 17:01:35.679 27194 27274 E AndroidRuntime: 	at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:243)
05-29 17:01:35.679 27194 27274 E AndroidRuntime: 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133)
05-29 17:01:35.679 27194 27274 E AndroidRuntime: 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607)
05-29 17:01:35.679 27194 27274 E AndroidRuntime: 	at java.lang.Thread.run(Thread.java:761)
05-29 17:01:35.679 27194 27274 E AndroidRuntime: Caused by: java.lang.SecurityException: Unable to start service Intent { act=com.google.android.apps.muzei.api.action.SUBSCRIBE cmp=de.devmil.muzei.bingimageofthedayartsource/de.devmil.muzei.bingimageoftheday.BingImageOfTheDayArtSource (has extras) }: AMS: *** Unable to launch app de.devmil.muzei.bingimageofthedayartsource/10155 for service Intent { act=com.google.android.apps.muzei.api.action.SUBSCRIBE cmp=de.devmil.muzei.bingimageofthedayartsource/de.devmil.muzei.bingimageoftheday.BingImageOfTheDayArtSource }, from net.nurik.roman.muzei/10156: AutoStart Limited.
05-29 17:01:35.679 27194 27274 E AndroidRuntime: 	at android.app.ContextImpl.startServiceCommon(ContextImpl.java:1397)
05-29 17:01:35.679 27194 27274 E AndroidRuntime: 	at android.app.ContextImpl.startService(ContextImpl.java:1370)
05-29 17:01:35.679 27194 27274 E AndroidRuntime: 	at android.content.ContextWrapper.startService(ContextWrapper.java:613)
05-29 17:01:35.679 27194 27274 E AndroidRuntime: 	at com.google.android.apps.muzei.SourceManager.unsubscribe(SourceManager.java:229)
05-29 17:01:35.679 27194 27274 E AndroidRuntime: 	at com.google.android.apps.muzei.SourceManager.access$100(SourceManager.java:53)
05-29 17:01:35.679 27194 27274 E AndroidRuntime: 	at com.google.android.apps.muzei.SourceManager$3.doInBackground(SourceManager.java:133)
05-29 17:01:35.679 27194 27274 E AndroidRuntime: 	at com.google.android.apps.muzei.SourceManager$3.doInBackground(SourceManager.java:118)
05-29 17:01:35.679 27194 27274 E AndroidRuntime: 	at android.os.AsyncTask$2.call(AsyncTask.java:304)
05-29 17:01:35.679 27194 27274 E AndroidRuntime: 	at java.util.concurrent.FutureTask.run(FutureTask.java:237)
05-29 17:01:35.679 27194 27274 E AndroidRuntime: 	... 4 more
05-29 17:02:10.388 27293 27412 E AndroidRuntime: FATAL EXCEPTION: AsyncTask #1
05-29 17:02:10.388 27293 27412 E AndroidRuntime: Process: net.nurik.roman.muzei, PID: 27293
05-29 17:02:10.388 27293 27412 E AndroidRuntime: java.lang.RuntimeException: An error occurred while executing doInBackground()
05-29 17:02:10.388 27293 27412 E AndroidRuntime: 	at android.os.AsyncTask$3.done(AsyncTask.java:318)
05-29 17:02:10.388 27293 27412 E AndroidRuntime: 	at java.util.concurrent.FutureTask.finishCompletion(FutureTask.java:354)
05-29 17:02:10.388 27293 27412 E AndroidRuntime: 	at java.util.concurrent.FutureTask.setException(FutureTask.java:223)
05-29 17:02:10.388 27293 27412 E AndroidRuntime: 	at java.util.concurrent.FutureTask.run(FutureTask.java:242)
05-29 17:02:10.388 27293 27412 E AndroidRuntime: 	at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:243)
05-29 17:02:10.388 27293 27412 E AndroidRuntime: 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133)
05-29 17:02:10.388 27293 27412 E AndroidRuntime: 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607)
05-29 17:02:10.388 27293 27412 E AndroidRuntime: 	at java.lang.Thread.run(Thread.java:761)
05-29 17:02:10.388 27293 27412 E AndroidRuntime: Caused by: java.lang.SecurityException: Unable to start service Intent { act=com.google.android.apps.muzei.api.action.SUBSCRIBE cmp=de.devmil.muzei.bingimageofthedayartsource/de.devmil.muzei.bingimageoftheday.BingImageOfTheDayArtSource (has extras) }: AMS: *** Unable to launch app de.devmil.muzei.bingimageofthedayartsource/10155 for service Intent { act=com.google.android.apps.muzei.api.action.SUBSCRIBE cmp=de.devmil.muzei.bingimageofthedayartsource/de.devmil.muzei.bingimageoftheday.BingImageOfTheDayArtSource }, from net.nurik.roman.muzei/10156: AutoStart Limited.
05-29 17:02:10.388 27293 27412 E AndroidRuntime: 	at android.app.ContextImpl.startServiceCommon(ContextImpl.java:1397)
05-29 17:02:10.388 27293 27412 E AndroidRuntime: 	at android.app.ContextImpl.startService(ContextImpl.java:1370)
05-29 17:02:10.388 27293 27412 E AndroidRuntime: 	at android.content.ContextWrapper.startService(ContextWrapper.java:613)
05-29 17:02:10.388 27293 27412 E AndroidRuntime: 	at com.google.android.apps.muzei.SourceManager.unsubscribe(SourceManager.java:229)
05-29 17:02:10.388 27293 27412 E AndroidRuntime: 	at com.google.android.apps.muzei.SourceManager.access$100(SourceManager.java:53)
05-29 17:02:10.388 27293 27412 E AndroidRuntime: 	at com.google.android.apps.muzei.SourceManager$3.doInBackground(SourceManager.java:133)
05-29 17:02:10.388 27293 27412 E AndroidRuntime: 	at com.google.android.apps.muzei.SourceManager$3.doInBackground(SourceManager.java:118)
05-29 17:02:10.388 27293 27412 E AndroidRuntime: 	at android.os.AsyncTask$2.call(AsyncTask.java:304)
05-29 17:02:10.388 27293 27412 E AndroidRuntime: 	at java.util.concurrent.FutureTask.run(FutureTask.java:237)
05-29 17:02:10.388 27293 27412 E AndroidRuntime: 	... 4 more
05-29 17:34:42.066   920   920 E AndroidRuntime: FATAL EXCEPTION: main```

**Comment by ianhanniballake** [comment]
The stack trace you have provided does not seem to correlate with Muzei's codebase (we already catch and handle SecurityExceptions), but from looking at the exception message "AutoStart Limited", you must disable battery optimizations on the Bing Image of the Day source that you are using.

**Comment by liobash** [comment]
Hi @ianhanniballake, thank you for your prompt feedback. I am sorry if this caused any in inconvenience but please could you make clear what you meant by  
> The stack trace you have provided does not seem to correlate with Muzei's codebase

Although i could be wrong. I just uninstalled the application and reinstall and attempt to launch the app again. This time, it crashed on first click on ACTIVATE.

**Comment by ianhanniballake** [comment]
I'm saying that the stack trace you provided is not something that Muzei 2.5.2 could produce - the `AsyncTask` mentioned in the stack trace is not a class we use anymore. Muzei also specifically catches and handles the `SecurityException` that your stack trace says we do not catch and handle. Perhaps a much older version of Muzei could produce that stack trace...

Like I said, disabling battery optimizations via the Settings app on the Bing Image of the Day source would be enough to prevent this crash, no matter what version of Muzei you are using. This is a limitation of the current Muzei API and something being addressed in a new version of the API in development.
